import { Link, useLoaderData } from "react-router";
import { listProjects } from "~/services/project-store.server";

export async function loader() {
  const projects = await listProjects();

  return {
    projects,
  };
}

export function meta() {
  return [
    { title: "Projects | DramaCommerce AI" },
    {
      name: "description",
      content: "View generated product drama ad projects.",
    },
  ];
}

export default function ProjectsIndex() {
  const { projects } = useLoaderData<typeof loader>();

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-10 text-white">
      <div className="mx-auto max-w-6xl">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-400">
              DramaCommerce AI
            </p>

            <h1 className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">
              Generated Projects
            </h1>

            <p className="mt-4 max-w-2xl text-slate-300">
              Browse product drama ad plans generated by the AI showrunner.
            </p>
          </div>

          <Link
            to="/generate"
            className="rounded-xl bg-white px-5 py-3 font-semibold text-slate-950 transition hover:bg-slate-200"
          >
            Generate New
          </Link>
        </div>

        {projects.length === 0 ? (
          <section className="mt-10 rounded-2xl border border-white/10 bg-white/5 p-8 text-center">
            <h2 className="text-2xl font-bold">No projects yet</h2>
            <p className="mt-3 text-slate-400">
              Generate your first product drama ad plan.
            </p>

            <Link
              to="/generate"
              className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 font-semibold text-slate-950 transition hover:bg-slate-200"
            >
              Start Generating
            </Link>
          </section>
        ) : (
          <section className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
            {projects.map((project) => {
              const showPlan = project.showPlan;

              return (
                <Link
                  key={project.id}
                  to={`/projects/${project.id}`}
                  className="group overflow-hidden rounded-2xl border border-white/10 bg-white/5 transition hover:border-white/25 hover:bg-white/10"
                >
                  {showPlan.brief.imageUrl ? (
                    <div className="flex h-48 items-center justify-center bg-slate-900">
                      <img
                        src={showPlan.brief.imageUrl}
                        alt={showPlan.brief.productName}
                        className="h-full w-full object-contain p-4 transition group-hover:scale-105"
                      />
                    </div>
                  ) : (
                    <div className="flex h-48 items-center justify-center bg-slate-900 text-slate-500">
                      No image
                    </div>
                  )}

                  <div className="p-5">
                    <div className="flex items-center justify-between gap-3">
                      <span
                        className={
                          showPlan.source === "qwen"
                            ? "rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-200"
                            : "rounded-full bg-amber-400/10 px-3 py-1 text-xs font-semibold text-amber-200"
                        }
                      >
                        {showPlan.source === "qwen" ? "Qwen" : "Mock"}
                      </span>

                      <span className="text-xs text-slate-500">
                        {new Date(project.createdAt).toLocaleDateString()}
                      </span>
                    </div>

                    <h2 className="mt-4 line-clamp-2 text-xl font-bold">
                      {showPlan.brief.productName}
                    </h2>

                    <p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-400">
                      {showPlan.concept}
                    </p>

                    <div className="mt-5 grid grid-cols-2 gap-3 text-xs text-slate-400">
                      <div className="rounded-lg bg-slate-900 p-3">
                        <p className="text-slate-500">Platform</p>
                        <p className="mt-1 font-medium text-slate-200">
                          {showPlan.brief.platform}
                        </p>
                      </div>

                      <div className="rounded-lg bg-slate-900 p-3">
                        <p className="text-slate-500">Mood</p>
                        <p className="mt-1 font-medium text-slate-200">
                          {showPlan.brief.mood}
                        </p>
                      </div>
                    </div>
                  </div>
                </Link>
              );
            })}
          </section>
        )}
      </div>
    </main>
  );
}
