import type { ReactNode } from "react";
import { Link, useLoaderData } from "react-router";
import type { LoaderFunctionArgs } from "react-router";
import { getProject } from "~/services/project-store.server";

export async function loader({ params }: LoaderFunctionArgs) {
  const projectId = params.projectId;

  if (!projectId) {
    throw new Response("Project ID is required", { status: 400 });
  }

  const project = await getProject(projectId);

  if (!project) {
    throw new Response("Project not found", { status: 404 });
  }

  return project;
}

export function meta() {
  return [
    { title: "Generated Project | DramaCommerce AI" },
    {
      name: "description",
      content: "Generated product drama ad plan.",
    },
  ];
}

export default function ProjectDetail() {
  const project = useLoaderData<typeof loader>();
  const result = project.showPlan;

  return (
    <main className="min-h-screen bg-slate-950 px-6 py-10 text-white">
      <div className="mx-auto max-w-6xl">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <Link to="/generate" className="text-sm text-slate-400 hover:text-white">
            ← Generate another product drama
          </Link>

          <p className="text-sm text-slate-500">
            Created at {new Date(project.createdAt).toLocaleString()}
          </p>
        </div>

        <section className="mt-10">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-400">
            DramaCommerce AI
          </p>

          <h1 className="mt-4 text-4xl font-bold tracking-tight md:text-5xl">
            {result.brief.productName}
          </h1>

          <p className="mt-4 max-w-2xl text-slate-300">
            AI-generated product drama ad plan for {result.brief.platform}.
          </p>

          {result.brief.imageUrl ? (
            <div className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/5">
              <img
                src={result.brief.imageUrl}
                alt={result.brief.productName}
                className="max-h-[420px] w-full object-contain p-4"
              />
            </div>
          ) : null}

        </section>

        <section className="mt-8 space-y-5">
          <div
            className={
              result.source === "qwen"
                ? "rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-5"
                : "rounded-2xl border border-amber-400/20 bg-amber-400/10 p-5"
            }
          >
            <p
              className={
                result.source === "qwen"
                  ? "text-sm font-semibold text-emerald-200"
                  : "text-sm font-semibold text-amber-200"
              }
            >
              {result.source === "qwen"
                ? "Generated by Qwen Cloud."
                : "Using mock fallback."}
            </p>

            <p
              className={
                result.source === "qwen"
                  ? "mt-2 text-sm text-emerald-100/80"
                  : "mt-2 text-sm text-amber-100/80"
              }
            >
              {result.source === "qwen"
                ? "The showrunner pipeline used Qwen to generate this product drama plan."
                : "Qwen environment variables are not configured yet, so the app generated a local mock plan."}
            </p>
          </div>

          <ResultCard title="Brief">
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              <SmallItem label="Product" value={result.brief.productName} />
              <SmallItem label="Image" value={result.brief.imageName} />
              <SmallItem label="Audience" value={result.brief.targetAudience} />
              <SmallItem label="Mood" value={result.brief.mood} />
              <SmallItem label="Platform" value={result.brief.platform} />
              <SmallItem label="Duration" value={result.brief.duration} />
            </div>
          </ResultCard>

          <ResultCard title="Story Concept">
            <p className="text-slate-300">{result.concept}</p>
          </ResultCard>

          <ResultCard title="Hook">
            <p className="text-2xl font-bold leading-snug">“{result.hook}”</p>
          </ResultCard>

          <ResultCard title="Voice-over">
            <p className="leading-7 text-slate-300">{result.voiceOver}</p>
          </ResultCard>

          <ResultCard title="Storyboard">
            <div className="space-y-4">
              {result.storyboard.map((scene) => (
                <div
                  key={scene.scene}
                  className="rounded-xl border border-white/10 bg-slate-900 p-4"
                >
                  <p className="text-xs uppercase tracking-wide text-slate-500">
                    Scene {scene.scene} · {scene.duration}
                  </p>

                  <h3 className="mt-1 font-bold">{scene.title}</h3>

                  <p className="mt-3 text-sm leading-6 text-slate-300">
                    {scene.visual}
                  </p>

                  <p className="mt-3 rounded-lg bg-white/5 p-3 text-sm text-slate-300">
                    <span className="font-semibold text-white">Voice-over:</span>{" "}
                    {scene.voiceOver}
                  </p>

                  <p className="mt-3 rounded-lg bg-indigo-400/10 p-3 text-sm leading-6 text-indigo-100">
                    <span className="font-semibold text-white">Video prompt:</span>{" "}
                    {scene.videoPrompt}
                  </p>
                </div>
              ))}
            </div>
          </ResultCard>

          <ResultCard title="Editing Timeline">
            <ol className="space-y-3">
              {result.timeline.map((item) => (
                <li
                  key={item}
                  className="rounded-xl border border-white/10 bg-slate-900 p-4 text-sm text-slate-300"
                >
                  {item}
                </li>
              ))}
            </ol>
          </ResultCard>

          <ResultCard title="Social Caption">
            <p className="leading-7 text-slate-300">{result.caption}</p>
            <p className="mt-4 text-lg font-bold">{result.cta}</p>
          </ResultCard>
        </section>
      </div>
    </main>
  );
}

function ResultCard({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-white/10 bg-white/5 p-6">
      <h2 className="text-xl font-bold">{title}</h2>
      <div className="mt-4">{children}</div>
    </section>
  );
}

function SmallItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-white/10 bg-slate-900 p-4">
      <p className="text-xs uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-1 text-sm font-medium text-slate-100">{value}</p>
    </div>
  );
}
